apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: box
  name: box
spec:
  replicas: 1
  selector:
    matchLabels:
      app: box
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: box
    spec:
      containers:
      - image: setthapong/box
        name: box
        resources: {}
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: box-service
  labels:
    app: box
spec:
  type: NodePort
  selector:
    app: box
  ports:
    - port: 4200
      targetPort: 4200
      nodePort: 30042
